### ISSUE TITLE
There were problems loading project .csproj

### ISSUE THREAD

**Issue by preichling** [godotengine/godot-csharp-vscode#58]
Windows 10/ Godot 4.1 .NET

Whenever I open a cs file, I get the following error: 
![image](https://github.com/godotengine/godot-csharp-vscode/assets/23247230/d3d02fc3-18ab-4a6b-8f49-458436fc05d2)

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# standalone...
[Info  - 9:16:11 PM] [Program]Language server initialized
[Info  - 9:16:11 PM] [LanguageServerProjectSystem]Loaded MSBuild at C:\Program Files\dotnet\sdk\7.0.203
[Info  - 9:16:11 PM] [LanguageServerProjectSystem]Loading h:\Coding Projects\GoDotGames\First3d\squash_the_creeps_start_1.1.0\Squash the Creeps (3D).sln...
[Error - 9:16:12 PM] [LanguageServerProjectSystem]Exception thrown while loading h:\Coding Projects\GoDotGames\First3d\squash_the_creeps_start_1.1.0\Squash the Creeps (3D).csproj System.InvalidOperationException: Compilation options cannot be null for C#/VB project - line 147
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LoadedProject.UpdateWithNewProjectInfoAsync(ProjectFileInfo newProjectInfo) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs:line 147
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LoadedProject.UpdateWithNewProjectInfoAsync(ProjectFileInfo newProjectInfo) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LoadedProject.cs:line 149
   at Microsoft.CodeAnalysis.LanguageServer.HostWorkspace.LanguageServerProjectSystem.LoadOrReloadProjectAsync(ProjectToLoad projectToLoad, ProjectBuildManager projectBuildManager, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/HostWorkspace/LanguageServerProjectSystem.cs:line 275
[Info  - 9:16:12 PM] [LanguageServerProjectSystem]Completed (re)load of all projects in 00:00:00.2478341

I set up the editor path in the plugins settings(which this is the only setting that is returned): 

![image](https://github.com/godotengine/godot-csharp-vscode/assets/23247230/25fcdf01-e76c-40e7-b2a1-36bace65bdac)

![image](https://github.com/godotengine/godot-csharp-vscode/assets/23247230/89dbebf8-bd16-4b48-9b52-0bdb621fbde0)

**Comment by raulsntos** [comment]
The VSCode error shows that the source of the error is [Microsoft's C# extension](https://github.com/dotnet/vscode-csharp/). Sounds like it may be related to https://github.com/dotnet/vscode-csharp/issues/6356.

**Comment by BanMengma** [comment]
Have a similar issue when I work on my Unity project. Solved by following this link https://forum.unity.com/threads/microsoft-previews-unity-extension-for-visual-studio-code.1468913/. Update the Visual Stuidio Editor in Unity to newest version. So if you are in the Unity project and facing the issue in this topic, try this and hope it can help you. Gook luck. 8)

**Comment by raulsntos** [comment]
Closing as fixed upstream. If you still have this issue, open a new issue on the [Microsoft C# VSCode extension](https://github.com/dotnet/vscode-csharp/issues/new) repository.
