### ISSUE TITLE
Intellisense randomly stops working out of nowher

### ISSUE THREAD

**Issue by moonwirer** [godotengine/godot-csharp-vscode#65]
**OS/device including version:**
Linux Mint 21.3, Godot 4.3

**Issue description:**
Frequently now, the intellisense for Godot randomly fails and shuts down, making it so no errors are reported, documentation becomes unavailable and the colour-coded types are gone.

**Log:**
```
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] {"pipeName":"/tmp/3c06f875.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 15:54:34] [Program] Language server initialized
[Info  - 15:54:41] [WorkspaceProjectFactoryService] Project /home/whitecat/Documents/Godot/Puzzle/Puzzle.csproj loaded by C# Dev Kit
[Error - 16:02:16] [LanguageServerHost] System.ArgumentException: '<Documentf0db74e0-ba1e-46be-a66b-359bdd57bbc8>' is not part of the workspace.
   at Microsoft.CodeAnalysis.Workspace.<>c.<OnDocumentClosedEx>b__213_0(Solution oldSolution, ValueTuple`4 data) in /_/src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs:line 662
   at Microsoft.CodeAnalysis.Workspace.SetCurrentSolutionAsync[TData](Boolean useAsync, TData data, Func`3 transformation, Boolean mayRaiseEvents, Action`3 onBeforeUpdate, Action`3 onAfterUpdate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Workspace.cs:line 511
   at Roslyn.Utilities.ValueTaskExtensions.VerifyCompleted[T](ValueTask`1 task, String message) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ValueTaskExtensions.cs:line 21
   at Microsoft.CodeAnalysis.Workspace.SetCurrentSolution[TData](TData data, Func`3 transformation, Boolean mayRaiseEvents, Action`3 onBeforeUpdate, Action`3 onAfterUpdate) in /_/src/Workspaces/Core/Portable/Workspace/Workspace.cs:line 472
   at Microsoft.CodeAnalysis.Workspace.OnDocumentClosedEx(DocumentId documentId, TextLoader reloader, Boolean requireDocumentPresentAndOpen) in /_/src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs:line 650
   at Microsoft.CodeAnalysis.PdbSourceDocument.PdbSourceDocumentMetadataAsSourceFileProvider.TryRemoveDocumentFromWorkspace(MetadataAsSourceWorkspace workspace, String filePath) in /_/src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs:line 385
   at Microsoft.CodeAnalysis.MetadataAsSource.MetadataAsSourceFileService.TryRemoveDocumentFromWorkspace(String filePath) in /_/src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs:line 203
   at Microsoft.CodeAnalysis.LanguageServer.LspMiscellaneousFilesWorkspace.TryRemoveMiscellaneousDocument(Uri uri, Boolean removeFromMetadataWorkspace) in /_/src/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspace.cs:line 80
   at Microsoft.CodeAnalysis.LanguageServer.LspWorkspaceManager.StopTrackingAsync(Uri uri, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs:line 199
   at Microsoft.CodeAnalysis.LanguageServer.Handler.DocumentChanges.DidCloseHandler.HandleNotificationAsync(DidCloseTextDocumentParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/DocumentChanges/DidCloseHandler.cs:line 36
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 199
[Error - 16:02:16] [LanguageServerHost] System.ArgumentException: '<Documentf0db74e0-ba1e-46be-a66b-359bdd57bbc8>' is not part of the workspace.
   at Microsoft.CodeAnalysis.Workspace.<>c.<OnDocumentClosedEx>b__213_0(Solution oldSolution, ValueTuple`4 data) in /_/src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs:line 662
   at Microsoft.CodeAnalysis.Workspace.SetCurrentSolutionAsync[TData](Boolean useAsync, TData data, Func`3 transformation, Boolean mayRaiseEvents, Action`3 onBeforeUpdate, Action`3 onAfterUpdate, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/Workspace/Workspace.cs:line 511
   at Roslyn.Utilities.ValueTaskExtensions.VerifyCompleted[T](ValueTask`1 task, String message) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/ValueTaskExtensions.cs:line 21
   at Microsoft.CodeAnalysis.Workspace.SetCurrentSolution[TData](TData data, Func`3 transformation, Boolean mayRaiseEvents, Action`3 onBeforeUpdate, Action`3 onAfterUpdate) in /_/src/Workspaces/Core/Portable/Workspace/Workspace.cs:line 472
   at Microsoft.CodeAnalysis.Workspace.OnDocumentClosedEx(DocumentId documentId, TextLoader reloader, Boolean requireDocumentPresentAndOpen) in /_/src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs:line 650
   at Microsoft.CodeAnalysis.PdbSourceDocument.PdbSourceDocumentMetadataAsSourceFileProvider.TryRemoveDocumentFromWorkspace(MetadataAsSourceWorkspace workspace, String filePath) in /_/src/Features/Core/Portable/PdbSourceDocument/PdbSourceDocumentMetadataAsSourceFileProvider.cs:line 385
   at Microsoft.CodeAnalysis.MetadataAsSource.MetadataAsSourceFileService.TryRemoveDocumentFromWorkspace(String filePath) in /_/src/Features/Core/Portable/MetadataAsSource/MetadataAsSourceFileService.cs:line 203
   at Microsoft.CodeAnalysis.LanguageServer.LspMiscellaneousFilesWorkspace.TryRemoveMiscellaneousDocument(Uri uri, Boolean removeFromMetadataWorkspace) in /_/src/LanguageServer/Protocol/Workspaces/LspMiscellaneousFilesWorkspace.cs:line 80
   at Microsoft.CodeAnalysis.LanguageServer.LspWorkspaceManager.StopTrackingAsync(Uri uri, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs:line 199
   at Microsoft.CodeAnalysis.LanguageServer.Handler.DocumentChanges.DidCloseHandler.HandleNotificationAsync(DidCloseTextDocumentParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/DocumentChanges/DidCloseHandler.cs:line 36
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 199
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 241
   at Microsoft.CodeAnalysis.LanguageServer.RoslynRequestExecutionQueue.WrapStartRequestTaskAsync(Task nonMutatingRequestTask, Boolean rethrowExceptions) in /_/src/LanguageServer/Protocol/RoslynRequestExecutionQueue.cs:line 40
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueCoreAsync[TRequest,TResponse](IQueueItem`1 work, IMethodHandler handler, RequestHandlerMetadata metadata, ConcurrentDictionary`2 concurrentlyExecutingTasks, CancellationTokenSource currentWorkCts, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 349
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.InvokeProcessCoreAsync(IQueueItem`1 work, RequestHandlerMetadata metadata, IMethodHandler handler, MethodInfo methodInfo, ConcurrentDictionary`2 concurrentlyExecutingTasks, CancellationTokenSource currentWorkCts, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 302
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueAsync() in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 254
[Info  - 16:02:16] Error processing queue, shutting down
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/elements/FloorButton.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/elements/LaserCatcher.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/areas/TriggerSubtitle.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/elements/LaserCatcher.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/elements/FloorButton.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/elements/FloorButton.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/elements/LaserCatcher.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Request textDocument/diagnostic failed.
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Error - 16:02:16] Document pull failed for text document file:///home/whitecat/Documents/Godot/Puzzle/scripts/areas/TriggerSubtitle.cs
  Message: Server was requested to shut down.
  Code: -32000 
[object Object]
[Info  - 16:02:16] Connection to server got closed. Server will restart.
true
Using dotnet configured on PATH
Dotnet path: /usr/lib/dotnet/dotnet
Activating C# + C# Dev Kit...
waiting for named pipe information from server...
[stdout] fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/whitecat/.vscode/extensions/ms-dotnettools.csharp-2.46.32-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/whitecat/.vscode/extensions/ms-dotnettools.csharp-2.46.32-linux-x64/.xamlTools
fail: Microsoft.CodeAnalysis.LanguageServer.ExportProviderBuilder[0]
      /home/whitecat/.vscode/extensions/ms-dotnettools.csharp-2.46.32-linux-x64/.xamlTools/Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics.dll with assembly name Microsoft.VisualStudio.DesignTools.CodeAnalysis.Diagnostics, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a conflicts with extension loaded from /home/whitecat/.vscode/extensions/ms-dotnettools.csharp-2.46.32-linux-x64/.xamlTools
[stdout] {"pipeName":"/tmp/c8bddea7.sock"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 16:02:17] [Program] Language server initialized
```

**Comment by raulsntos** [comment]
This extension only supports Godot 3, and IntelliSense is not provided by this extension anyway. That's provided by [Microsoft's C# extension](https://github.com/dotnet/vscode-csharp/) so issues with IntelliSense should be reported there.
